export const blogData = [
  {
    id:1,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/articles/blog-3_1200x.jpg?v=1605604095",
    header: "Portable Bluetooth Speaker with Light up Logo",
    date: "November 17, 2020",
    author: "Vinova Theme",
    comments: 0,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut iaculis arcu. Proin tincidunt neque, vehicula euismod lorem.",
  },
  {
    id:2,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/articles/blog-3_1200x.jpg?v=1605604095",
    header: "Smart Watch with Health Tracking Features",
    date: "December 1, 2020",
    author: "TechPulse",
    comments: 5,
    text: "Track your heart rate, sleep, and more with this new generation smart watch. A must-have for fitness lovers.",
  },
  {
    id:3,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/articles/blog-1_1200x.jpg?v=1605604033",
    header: "Minimalist Wooden Desk Organizer",
    date: "January 5, 2021",
    author: "Design Hub",
    comments: 2,
    text: "Keep your workspace clutter-free with this elegant bamboo desk organizer. Fits any modern workspace perfectly.",
  },
  {
    id:4,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/articles/blog-2_1200x.jpg?v=1605604021",
    header: "Insulated Travel Coffee Mug",
    date: "February 10, 2021",
    author: "MugLife",
    comments: 4,
    text: "Stay caffeinated all day long with this leak-proof insulated mug. Keeps drinks hot for 12 hours!",
  },
  {
    id:5,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-1_1920x.jpg?v=1613734945",
    header: "Anti-Theft USB Charging Backpack",
    date: "March 15, 2021",
    author: "Urban Traveler",
    comments: 6,
    text: "Perfect for digital nomads, this backpack includes hidden zippers and built-in USB charging ports.",
  },
  {
    id:6,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-2_1920x.jpg?v=1613734945",
    header: "2025 Daily Productivity Planner",
    date: "August 30, 2025",
    author: "Productive You",
    comments: 0,
    text: "Plan your days with this clean and simple productivity planner. Includes habit tracking and reflection pages.",
  },
  {
    id:7,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-7_1920x1920.jpg?v=1613734945",
    header: "LED Desk Lamp with Wireless Charger",
    date: "April 22, 2021",
    author: "LightWorks",
    comments: 1,
    text: "Brighten your workspace with this multi-function LED lamp. Adjustable brightness and built-in Qi charger.",
  },
  {
    id:8,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-8_1920x1920.jpg?v=1613734945",
    header: "True Wireless Noise-Cancelling Earbuds",
    date: "June 7, 2021",
    author: "SoundWave",
    comments: 10,
    text: "Experience immersive sound with these high-quality noise-cancelling earbuds. Great for calls and music.",
  },
  {
    id:9,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/about_1170x.jpg?v=1613735000",
    header: "Adjustable Standing Desk Converter",
    date: "July 18, 2021",
    author: "WorkSmart",
    comments: 3,
    text: "Easily switch from sitting to standing with this adjustable desk converter. Boost productivity and health.",
  },
  {
    id:10,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-1_1920x.jpg?v=1613734945",
    header: "Eco-Friendly Reusable Notebook",
    date: "September 1, 2021",
    author: "GreenPaper",
    comments: 0,
    text: "Save paper and take notes sustainably. Wipe clean and reuse again and again with any erasable pen.",
  },
  {
    id:11,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/articles/blog-3_1200x.jpg?v=1605604095",
    header: "Aluminum Phone and Tablet Stand",
    date: "October 5, 2021",
    author: "DeskMate",
    comments: 2,
    text: "Adjustable stand for phones and tablets — perfect for video calls, watching, or reading hands-free.",
  },
  {
    id:12,
    url: "https://nuranium-furniture.myshopify.com/cdn/shop/files/img-21-7_1920x1920.jpg?v=1613734945",
    header: "Compact 4K Action Camera",
    date: "November 10, 2021",
    author: "ActionX",
    comments: 8,
    text: "Capture adventures in stunning 4K with this durable, waterproof action camera. Includes mounts.",
  }
];
